process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP208 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP210 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP214 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP218 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP241 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP345 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP362 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP369 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP370 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP376 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP377 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP378 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP379 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP382 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP383 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP384 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP386 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP387 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP388 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP389 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP391 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP392 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP393 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP394 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP397 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP398 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP400 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP402 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP403 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP405 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP406 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP408 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP409 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP410 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP411 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP412 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP415 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP416 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP417 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP418 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP419 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP420 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP423 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP424 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP425 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP426 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP427 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP428 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP429 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP433 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP434 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP435 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP436 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP437 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP438 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP440 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP441 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP442 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP445 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP446 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP447 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP448 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP449 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP450 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP453 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP454 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP456 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP458 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP459 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP461 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP462 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP465 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP467 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP470 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP473 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
process_meg.py -remove_old -bids_root /data/EnigmaMeg/BIDS/UPITT_Age_HCP/BIDS -subject HCP480 -run 01 -session 1 -mains 60 -rest_tag eyesopen -emptyroom_tag empty -n_jobs 6
